[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
api = {path = "../api" }
services = {path = "../services"}
storage = {path = "../storage"}
types = {path = "../types"}
async-stream.workspace = true
axum.workspace = true
axum-macros.workspace = true
datastar.workspace = true
futures.workspace = true
maud.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"
